apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    namespace: quarkus-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: keycloak
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 15.1.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
