apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 8.4.5
    chart: grafana
  destination:
    namespace: quarkus-demo
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true