apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  source:
    chart: keycloak
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 15.1.3
    helm:
      parameters:
        - name: auth.adminPassword
          value: thisshouldbesecret
        - name: auth.managementPassword
          value: thisshouldbesecret
        - name: postgresql.auth.password
          value: thisshouldbesecret
        - name: postgresql.auth.postgresPassword
          value: thisshouldbesecret
  destination:
    namespace: quarkus-demo
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
